<?php

namespace Railroad\Railtracker\Tests\Resources;

class IpApiStubDataProvider
{
    public static function data()
    {
        return [
            'input' => array(
                '221.160.7.23',
                '211.102.48.29',
                '110.243.9.82',
                '212.191.124.225',
                '108.207.241.21',
                '4.0.98.201',
                '169.27.178.21',
                '71.209.226.27',
                '16.34.109.211',
                '208.206.232.146',
                '42.185.85.48',
                '64.45.47.98',
                '156.78.199.230',
                '83.127.166.129',
                '173.72.165.8',
                '211.100.74.117',
                '166.110.221.160',
                '192.81.138.80',
                '179.202.255.108',
                '255.204.8.63',
                '59.105.171.39',
                '140.233.83.33',
                '83.154.223.119',
                '22.178.28.39',
                '23.115.140.14',
                '77.38.153.144',
                '175.24.120.190',
                '89.190.143.245',
                '168.128.11.175',
                '246.10.125.95',
                '129.113.176.194',
                '245.247.226.47',
                '241.108.68.46',
                '3.30.130.33',
                '90.189.20.122',
                '209.70.55.5',
                '157.232.86.21',
                '113.21.11.113',
                '189.175.224.186',
                '143.248.55.35',
                '160.215.19.196',
                '11.176.98.99',
                '79.122.240.19',
                '94.172.217.251',
                '236.6.26.242',
                '121.52.136.237',
                '10.168.133.169',
                '76.197.118.230',
                '210.180.169.106',
                '209.162.246.127',
                '233.186.37.142',
                '221.221.108.218',
                '143.236.4.47',
                '132.19.95.187',
                '146.157.14.105',
                '34.236.215.44',
                '246.57.188.185',
                '69.18.88.244',
                '232.212.19.125',
                '28.88.69.104',
                '145.241.105.173',
                '85.114.52.226',
                '230.36.9.227',
                '249.208.123.64',
                '144.89.218.103',
                '23.34.16.9',
                '250.31.116.167',
                '101.135.222.110',
                '244.214.86.17',
                '254.51.118.104',
                '148.67.26.187',
                '169.148.83.54',
                '5.10.165.236',
                '204.190.205.202',
                '134.119.131.89',
                '202.51.99.67',
                '21.185.223.135',
                '44.156.133.181',
                '231.182.79.72',
                '221.107.128.75',
                '232.136.82.223',
                '68.133.79.32',
                '73.232.115.218',
                '11.245.118.113',
                '243.99.14.239',
                '155.33.44.46',
                '15.59.81.225',
                '208.53.193.173',
                '15.87.28.33',
                '54.128.36.11',
                '230.140.63.88',
                '189.173.147.116',
                '219.195.73.213',
                '121.39.149.24',
                '182.44.32.220',
                '216.252.36.175',
                '110.33.40.98',
                '217.49.230.132',
                '50.240.170.161',
                '145.166.46.140',
            ),
            'output' => array(
                0 => array(
                    'city' => 'Seongnam-si',
                    'country' => 'South Korea',
                    'countryCode' => 'KR',
                    'currency' => 'KRW',
                    'lat' => 37.3827,
                    'lon' => 127.119,
                    'query' => '221.160.7.23',
                    'region' => '41',
                    'regionName' => 'Gyeonggi-do',
                    'status' => 'success',
                    'timezone' => 'Asia/Seoul',
                    'zip' => '',
                ),
                1 => array(
                    'city' => 'Beijing',
                    'country' => 'China',
                    'countryCode' => 'CN',
                    'currency' => 'CNY',
                    'lat' => 39.904,
                    'lon' => 116.408,
                    'query' => '211.102.48.29',
                    'region' => 'BJ',
                    'regionName' => 'Beijing',
                    'status' => 'success',
                    'timezone' => 'Asia/Shanghai',
                    'zip' => '',
                ),
                2 => array(
                    'city' => 'Xingfeng',
                    'country' => 'China',
                    'countryCode' => 'CN',
                    'currency' => 'CNY',
                    'lat' => 39.7794,
                    'lon' => 116.52,
                    'query' => '110.243.9.82',
                    'region' => 'BJ',
                    'regionName' => 'Beijing',
                    'status' => 'success',
                    'timezone' => 'Asia/Shanghai',
                    'zip' => '',
                ),
                3 => array(
                    'city' => 'Lodz',
                    'country' => 'Poland',
                    'countryCode' => 'PL',
                    'currency' => 'PLN',
                    'lat' => 52.2555,
                    'lon' => 16.7424,
                    'query' => '212.191.124.225',
                    'region' => 'WP',
                    'regionName' => 'Greater Poland',
                    'status' => 'success',
                    'timezone' => 'Europe/Warsaw',
                    'zip' => '62-060',
                ),
                4 => array(
                    'city' => 'Leander',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 30.449,
                    'lon' => -97.9669,
                    'query' => '108.207.241.21',
                    'region' => 'TX',
                    'regionName' => 'Texas',
                    'status' => 'success',
                    'timezone' => 'America/Chicago',
                    'zip' => '78645',
                ),
                5 => array(
                    'city' => 'Newark',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 40.7357,
                    'lon' => -74.1724,
                    'query' => '4.0.98.201',
                    'region' => 'NJ',
                    'regionName' => 'New Jersey',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '07175',
                ),
                6 => array(
                    'city' => 'New York',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 40.7082,
                    'lon' => -74.0105,
                    'query' => '169.27.178.21',
                    'region' => 'NY',
                    'regionName' => 'New York',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '10271',
                ),
                7 => array(
                    'city' => 'Tempe',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 33.3908,
                    'lon' => -111.9184,
                    'query' => '71.209.226.27',
                    'region' => 'AZ',
                    'regionName' => 'Arizona',
                    'status' => 'success',
                    'timezone' => 'America/Phoenix',
                    'zip' => '85282',
                ),
                8 => array(
                    'city' => 'Palo Alto',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 37.4146,
                    'lon' => -122.146,
                    'query' => '16.34.109.211',
                    'region' => 'CA',
                    'regionName' => 'California',
                    'status' => 'success',
                    'timezone' => 'America/Los_Angeles',
                    'zip' => '94304',
                ),
                9 => array(
                    'city' => 'Washington D.C.',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 38.9072,
                    'lon' => -77.0369,
                    'query' => '208.206.232.146',
                    'region' => 'DC',
                    'regionName' => 'District of Columbia',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '20068',
                ),
                10 => array(
                    'city' => 'Harbin',
                    'country' => 'China',
                    'countryCode' => 'CN',
                    'currency' => 'CNY',
                    'lat' => 45.7423,
                    'lon' => 126.662,
                    'query' => '42.185.85.48',
                    'region' => 'HL',
                    'regionName' => 'Heilongjiang',
                    'status' => 'success',
                    'timezone' => 'Asia/Shanghai',
                    'zip' => '',
                ),
                11 => array(
                    'city' => 'Jacksonville',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 30.1365,
                    'lon' => -81.532,
                    'query' => '64.45.47.98',
                    'region' => 'FL',
                    'regionName' => 'Florida',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '32258',
                ),
                12 => array(
                    'city' => 'Northbrook',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 42.1147,
                    'lon' => -87.8752,
                    'query' => '156.78.199.230',
                    'region' => 'IL',
                    'regionName' => 'Illinois',
                    'status' => 'success',
                    'timezone' => 'America/Chicago',
                    'zip' => '60062',
                ),
                13 => array(
                    'city' => 'Frankfurt am Main',
                    'country' => 'Germany',
                    'countryCode' => 'DE',
                    'currency' => 'EUR',
                    'lat' => 50.1165,
                    'lon' => 8.62975,
                    'query' => '83.127.166.129',
                    'region' => 'HE',
                    'regionName' => 'Hesse',
                    'status' => 'success',
                    'timezone' => 'Europe/Berlin',
                    'zip' => '60486',
                ),
                14 => array(
                    'city' => 'Culpeper',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 38.5117,
                    'lon' => -77.9928,
                    'query' => '173.72.165.8',
                    'region' => 'VA',
                    'regionName' => 'Virginia',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '22701',
                ),
                15 => array(
                    'city' => 'Beijing',
                    'country' => 'China',
                    'countryCode' => 'CN',
                    'currency' => 'CNY',
                    'lat' => 39.9042,
                    'lon' => 116.407,
                    'query' => '211.100.74.117',
                    'region' => 'BJ',
                    'regionName' => 'Beijing',
                    'status' => 'success',
                    'timezone' => 'Asia/Shanghai',
                    'zip' => '',
                ),
                16 => array(
                    'city' => 'Santiago',
                    'country' => 'Chile',
                    'countryCode' => 'CL',
                    'currency' => 'CLP',
                    'lat' => -33.4393,
                    'lon' => -70.6474,
                    'query' => '166.110.221.160',
                    'region' => 'RM',
                    'regionName' => 'Santiago Metropolitan',
                    'status' => 'success',
                    'timezone' => 'America/Santiago',
                    'zip' => '8320000',
                ),
                17 => array(
                    'city' => 'Phoenix',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 33.4543,
                    'lon' => -112.074,
                    'query' => '192.81.138.80',
                    'region' => 'AZ',
                    'regionName' => 'Arizona',
                    'status' => 'success',
                    'timezone' => 'America/Phoenix',
                    'zip' => '85003',
                ),
                18 => array(
                    'city' => 'São Paulo',
                    'country' => 'Brazil',
                    'countryCode' => 'BR',
                    'currency' => 'BRL',
                    'lat' => -23.5505,
                    'lon' => -46.6333,
                    'query' => '179.202.255.108',
                    'region' => 'SP',
                    'regionName' => 'São Paulo',
                    'status' => 'success',
                    'timezone' => 'America/Sao_Paulo',
                    'zip' => '01000-000',
                ),
                19 => array('query' => '255.204.8.63', 'status' => 'fail',),
                20 => array(
                    'city' => 'Kanzijiao',
                    'country' => 'Taiwan',
                    'countryCode' => 'TW',
                    'currency' => 'TWD',
                    'lat' => 25.0936,
                    'lon' => 121.594,
                    'query' => '59.105.171.39',
                    'region' => '',
                    'regionName' => 'Taiwan',
                    'status' => 'success',
                    'timezone' => 'Asia/Taipei',
                    'zip' => '',
                ),
                21 => array(
                    'city' => 'Middlebury (village)',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 43.9919,
                    'lon' => -73.1716,
                    'query' => '140.233.83.33',
                    'region' => 'VT',
                    'regionName' => 'Vermont',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '05753',
                ),
                22 => array(
                    'city' => 'Aubervilliers',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'currency' => 'EUR',
                    'lat' => 48.9163,
                    'lon' => 2.3869,
                    'query' => '83.154.223.119',
                    'region' => 'IDF',
                    'regionName' => 'Île-de-France',
                    'status' => 'success',
                    'timezone' => 'Europe/Paris',
                    'zip' => '93300',
                ),
                23 => array(
                    'city' => 'Columbus',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 39.9829,
                    'lon' => -82.9105,
                    'query' => '22.178.28.39',
                    'region' => 'OH',
                    'regionName' => 'Ohio',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '43218',
                ),
                24 => array(
                    'city' => 'Santa Rosa',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 38.4592,
                    'lon' => -122.6393,
                    'query' => '23.115.140.14',
                    'region' => 'CA',
                    'regionName' => 'California',
                    'status' => 'success',
                    'timezone' => 'America/Los_Angeles',
                    'zip' => '95409',
                ),
                25 => array(
                    'city' => 'Riga',
                    'country' => 'Latvia',
                    'countryCode' => 'LV',
                    'currency' => 'EUR',
                    'lat' => 56.9496,
                    'lon' => 24.0978,
                    'query' => '77.38.153.144',
                    'region' => 'RIX',
                    'regionName' => 'Riga',
                    'status' => 'success',
                    'timezone' => 'Europe/Riga',
                    'zip' => '',
                ),
                26 => array(
                    'city' => 'Roubaix',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'currency' => 'EUR',
                    'lat' => 50.6927,
                    'lon' => 3.17785,
                    'query' => '175.24.120.190',
                    'region' => 'HDF',
                    'regionName' => 'Hauts-de-France',
                    'status' => 'success',
                    'timezone' => 'Europe/Paris',
                    'zip' => '59100',
                ),
                27 => array(
                    'city' => 'Reeuwijk',
                    'country' => 'Netherlands',
                    'countryCode' => 'NL',
                    'currency' => 'EUR',
                    'lat' => 52.047,
                    'lon' => 4.7222,
                    'query' => '89.190.143.245',
                    'region' => 'ZH',
                    'regionName' => 'South Holland',
                    'status' => 'success',
                    'timezone' => 'Europe/Amsterdam',
                    'zip' => '2811',
                ),
                28 => array(
                    'city' => 'Frankfurt am Main',
                    'country' => 'Germany',
                    'countryCode' => 'DE',
                    'currency' => 'EUR',
                    'lat' => 50.1109,
                    'lon' => 8.68213,
                    'query' => '168.128.11.175',
                    'region' => 'HE',
                    'regionName' => 'Hesse',
                    'status' => 'success',
                    'timezone' => 'Europe/Berlin',
                    'zip' => '60313',
                ),
                29 => array('query' => '246.10.125.95', 'status' => 'fail',),
                30 => array(
                    'city' => 'Edinburg',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 26.2823,
                    'lon' => -98.1825,
                    'query' => '129.113.176.194',
                    'region' => 'TX',
                    'regionName' => 'Texas',
                    'status' => 'success',
                    'timezone' => 'America/Chicago',
                    'zip' => '78539',
                ),
                31 => array('query' => '245.247.226.47', 'status' => 'fail',),
                32 => array('query' => '241.108.68.46', 'status' => 'fail',),
                33 => array(
                    'city' => 'Seattle',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 47.6223,
                    'lon' => -122.336,
                    'query' => '3.30.130.33',
                    'region' => 'WA',
                    'regionName' => 'Washington',
                    'status' => 'success',
                    'timezone' => 'America/Los_Angeles',
                    'zip' => '98109',
                ),
                34 => array(
                    'city' => 'Chita',
                    'country' => 'Russia',
                    'countryCode' => 'RU',
                    'currency' => 'RUB',
                    'lat' => 52.0515,
                    'lon' => 113.471,
                    'query' => '90.189.20.122',
                    'region' => 'ZAB',
                    'regionName' => 'Transbaikal Territory',
                    'status' => 'success',
                    'timezone' => 'Asia/Chita',
                    'zip' => '',
                ),
                35 => array(
                    'city' => 'Chicago',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 41.8781,
                    'lon' => -87.6298,
                    'query' => '209.70.55.5',
                    'region' => 'IL',
                    'regionName' => 'Illinois',
                    'status' => 'success',
                    'timezone' => 'America/Chicago',
                    'zip' => '60666',
                ),
                36 => array(
                    'city' => 'Herndon',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 38.9512,
                    'lon' => -77.3969,
                    'query' => '157.232.86.21',
                    'region' => 'VA',
                    'regionName' => 'Virginia',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '20171',
                ),
                37 => array(
                    'city' => 'Seoul',
                    'country' => 'South Korea',
                    'countryCode' => 'KR',
                    'currency' => 'KRW',
                    'lat' => 37.5454,
                    'lon' => 127.053,
                    'query' => '113.21.11.113',
                    'region' => '11',
                    'regionName' => 'Seoul',
                    'status' => 'success',
                    'timezone' => 'Asia/Seoul',
                    'zip' => '',
                ),
                38 => array(
                    'city' => 'Monterrey',
                    'country' => 'Mexico',
                    'countryCode' => 'MX',
                    'currency' => 'MXN',
                    'lat' => 25.6554,
                    'lon' => -100.3258,
                    'query' => '189.175.224.186',
                    'region' => 'NLE',
                    'regionName' => 'Nuevo León',
                    'status' => 'success',
                    'timezone' => 'America/Monterrey',
                    'zip' => '64720',
                ),
                39 => array(
                    'city' => 'Daejeon',
                    'country' => 'South Korea',
                    'countryCode' => 'KR',
                    'currency' => 'KRW',
                    'lat' => 36.3214,
                    'lon' => 127.4197,
                    'query' => '143.248.55.35',
                    'region' => '30',
                    'regionName' => 'Daejeon',
                    'status' => 'success',
                    'timezone' => 'Asia/Seoul',
                    'zip' => '',
                ),
                40 => array(
                    'city' => 'Chiyoda',
                    'country' => 'Japan',
                    'countryCode' => 'JP',
                    'currency' => 'JPY',
                    'lat' => 35.6906,
                    'lon' => 139.77,
                    'query' => '160.215.19.196',
                    'region' => '13',
                    'regionName' => 'Tokyo',
                    'status' => 'success',
                    'timezone' => 'Asia/Tokyo',
                    'zip' => '100-0001',
                ),
                41 => array(
                    'city' => 'Columbus',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 39.9829,
                    'lon' => -82.9105,
                    'query' => '11.176.98.99',
                    'region' => 'OH',
                    'regionName' => 'Ohio',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '43218',
                ),
                42 => array(
                    'city' => 'Moscow',
                    'country' => 'Russia',
                    'countryCode' => 'RU',
                    'currency' => 'RUB',
                    'lat' => 55.7946,
                    'lon' => 37.5664,
                    'query' => '79.122.240.19',
                    'region' => 'MOW',
                    'regionName' => 'Moscow',
                    'status' => 'success',
                    'timezone' => 'Europe/Moscow',
                    'zip' => '',
                ),
                43 => array(
                    'city' => 'Warsaw',
                    'country' => 'Poland',
                    'countryCode' => 'PL',
                    'currency' => 'PLN',
                    'lat' => 52.2184,
                    'lon' => 21.0418,
                    'query' => '94.172.217.251',
                    'region' => 'MZ',
                    'regionName' => 'Mazovia',
                    'status' => 'success',
                    'timezone' => 'Europe/Warsaw',
                    'zip' => '',
                ),
                44 => array('query' => '236.6.26.242', 'status' => 'fail',),
                45 => array(
                    'city' => 'Bandung',
                    'country' => 'Indonesia',
                    'countryCode' => 'ID',
                    'currency' => 'IDR',
                    'lat' => -6.9217,
                    'lon' => 107.6071,
                    'query' => '121.52.136.237',
                    'region' => 'JB',
                    'regionName' => 'West Java',
                    'status' => 'success',
                    'timezone' => 'Asia/Jakarta',
                    'zip' => '',
                ),
                46 => array('query' => '10.168.133.169', 'status' => 'fail',),
                47 => array(
                    'city' => 'Ashburn',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 39.0438,
                    'lon' => -77.4874,
                    'query' => '76.197.118.230',
                    'region' => 'VA',
                    'regionName' => 'Virginia',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '20149',
                ),
                48 => array(
                    'city' => 'Jungang-daero',
                    'country' => 'South Korea',
                    'countryCode' => 'KR',
                    'currency' => 'KRW',
                    'lat' => 35.1587,
                    'lon' => 129.064,
                    'query' => '210.180.169.106',
                    'region' => '26',
                    'regionName' => 'Busan',
                    'status' => 'success',
                    'timezone' => 'Asia/Seoul',
                    'zip' => '47210',
                ),
                49 => array(
                    'city' => 'Toronto',
                    'country' => 'Canada',
                    'countryCode' => 'CA',
                    'currency' => 'CAD',
                    'lat' => 43.6215,
                    'lon' => -79.392,
                    'query' => '209.162.246.127',
                    'region' => 'ON',
                    'regionName' => 'Ontario',
                    'status' => 'success',
                    'timezone' => 'America/Toronto',
                    'zip' => 'M5J',
                ),
                50 => array('query' => '233.186.37.142', 'status' => 'fail',),
                51 => array(
                    'city' => 'Beijing',
                    'country' => 'China',
                    'countryCode' => 'CN',
                    'currency' => 'CNY',
                    'lat' => 39.9288,
                    'lon' => 116.3889,
                    'query' => '221.221.108.218',
                    'region' => 'BJ',
                    'regionName' => 'Beijing',
                    'status' => 'success',
                    'timezone' => 'Asia/Shanghai',
                    'zip' => '',
                ),
                52 => array(
                    'city' => 'Stevens Point',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 44.5212,
                    'lon' => -89.5588,
                    'query' => '143.236.4.47',
                    'region' => 'WI',
                    'regionName' => 'Wisconsin',
                    'status' => 'success',
                    'timezone' => 'America/Chicago',
                    'zip' => '54481',
                ),
                53 => array(
                    'city' => 'Montgomery',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 32.4107,
                    'lon' => -86.2521,
                    'query' => '132.19.95.187',
                    'region' => 'AL',
                    'regionName' => 'Alabama',
                    'status' => 'success',
                    'timezone' => 'America/Chicago',
                    'zip' => '36114',
                ),
                54 => array(
                    'city' => 'Sierra Vista',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 31.5552,
                    'lon' => -110.35,
                    'query' => '146.157.14.105',
                    'region' => 'AZ',
                    'regionName' => 'Arizona',
                    'status' => 'success',
                    'timezone' => 'America/Phoenix',
                    'zip' => '85613',
                ),
                55 => array(
                    'city' => 'Ashburn',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 39.0438,
                    'lon' => -77.4874,
                    'query' => '34.236.215.44',
                    'region' => 'VA',
                    'regionName' => 'Virginia',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '20149',
                ),
                56 => array('query' => '246.57.188.185', 'status' => 'fail',),
                57 => array(
                    'city' => 'Plymouth',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 45.0042,
                    'lon' => -93.4554,
                    'query' => '69.18.88.244',
                    'region' => 'MN',
                    'regionName' => 'Minnesota',
                    'status' => 'success',
                    'timezone' => 'America/Chicago',
                    'zip' => '55441',
                ),
                58 => array('query' => '232.212.19.125', 'status' => 'fail',),
                59 => array(
                    'city' => 'Columbus',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 39.9747,
                    'lon' => -82.8948,
                    'query' => '28.88.69.104',
                    'region' => 'OH',
                    'regionName' => 'Ohio',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '43218',
                ),
                60 => array(
                    'city' => 'Vienna',
                    'country' => 'Austria',
                    'countryCode' => 'AT',
                    'currency' => 'EUR',
                    'lat' => 48.2082,
                    'lon' => 16.3738,
                    'query' => '145.241.105.173',
                    'region' => '9',
                    'regionName' => 'Vienna',
                    'status' => 'success',
                    'timezone' => 'Europe/Vienna',
                    'zip' => '',
                ),
                61 => array(
                    'city' => 'Petrcane',
                    'country' => 'Croatia',
                    'countryCode' => 'HR',
                    'currency' => 'HRK',
                    'lat' => 44.1883,
                    'lon' => 15.1605,
                    'query' => '85.114.52.226',
                    'region' => '13',
                    'regionName' => 'Zadarska',
                    'status' => 'success',
                    'timezone' => 'Europe/Zagreb',
                    'zip' => '23231',
                ),
                62 => array('query' => '230.36.9.227', 'status' => 'fail',),
                63 => array('query' => '249.208.123.64', 'status' => 'fail',),
                64 => array(
                    'city' => 'Beloit',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 42.562,
                    'lon' => -89.086,
                    'query' => '144.89.218.103',
                    'region' => 'WI',
                    'regionName' => 'Wisconsin',
                    'status' => 'success',
                    'timezone' => 'America/Chicago',
                    'zip' => '53511',
                ),
                65 => array(
                    'city' => 'Newark',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 40.7357,
                    'lon' => -74.1724,
                    'query' => '23.34.16.9',
                    'region' => 'NJ',
                    'regionName' => 'New Jersey',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '07175',
                ),
                66 => array('query' => '250.31.116.167', 'status' => 'fail',),
                67 => array(
                    'city' => 'Beijing',
                    'country' => 'China',
                    'countryCode' => 'CN',
                    'currency' => 'CNY',
                    'lat' => 39.9215,
                    'lon' => 116.443,
                    'query' => '101.135.222.110',
                    'region' => 'BJ',
                    'regionName' => 'Beijing',
                    'status' => 'success',
                    'timezone' => 'Asia/Shanghai',
                    'zip' => '',
                ),
                68 => array('query' => '244.214.86.17', 'status' => 'fail',),
                69 => array('query' => '254.51.118.104', 'status' => 'fail',),
                70 => array(
                    'city' => 'Chiyoda',
                    'country' => 'Japan',
                    'countryCode' => 'JP',
                    'currency' => 'JPY',
                    'lat' => 35.6906,
                    'lon' => 139.77,
                    'query' => '148.67.26.187',
                    'region' => '13',
                    'regionName' => 'Tokyo',
                    'status' => 'success',
                    'timezone' => 'Asia/Tokyo',
                    'zip' => '100-0001',
                ),
                71 => array(
                    'city' => 'Riyadh',
                    'country' => 'Saudi Arabia',
                    'countryCode' => 'SA',
                    'currency' => 'SAR',
                    'lat' => 24.7117,
                    'lon' => 46.7242,
                    'query' => '169.148.83.54',
                    'region' => '01',
                    'regionName' => 'Ar Riyāḑ',
                    'status' => 'success',
                    'timezone' => 'Asia/Riyadh',
                    'zip' => '',
                ),
                72 => array(
                    'city' => 'Münster',
                    'country' => 'Germany',
                    'countryCode' => 'DE',
                    'currency' => 'EUR',
                    'lat' => 51.9607,
                    'lon' => 7.62613,
                    'query' => '5.10.165.236',
                    'region' => 'NW',
                    'regionName' => 'North Rhine-Westphalia',
                    'status' => 'success',
                    'timezone' => 'Europe/Berlin',
                    'zip' => '48079',
                ),
                73 => array(
                    'city' => 'New York',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 40.7097,
                    'lon' => -74.0114,
                    'query' => '204.190.205.202',
                    'region' => 'NY',
                    'regionName' => 'New York',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '10006',
                ),
                74 => array(
                    'city' => 'Ismaning',
                    'country' => 'Germany',
                    'countryCode' => 'DE',
                    'currency' => 'EUR',
                    'lat' => 48.2356,
                    'lon' => 11.6808,
                    'query' => '134.119.131.89',
                    'region' => 'BY',
                    'regionName' => 'Bavaria',
                    'status' => 'success',
                    'timezone' => 'Europe/Berlin',
                    'zip' => '85737',
                ),
                75 => array(
                    'city' => 'Bogor',
                    'country' => 'Indonesia',
                    'countryCode' => 'ID',
                    'currency' => 'IDR',
                    'lat' => -6.5945,
                    'lon' => 106.789,
                    'query' => '202.51.99.67',
                    'region' => 'JB',
                    'regionName' => 'West Java',
                    'status' => 'success',
                    'timezone' => 'Asia/Jakarta',
                    'zip' => '',
                ),
                76 => array(
                    'city' => 'Columbus',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 39.9747,
                    'lon' => -82.8948,
                    'query' => '21.185.223.135',
                    'region' => 'OH',
                    'regionName' => 'Ohio',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '43218',
                ),
                77 => array(
                    'city' => 'San Diego',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 32.8187,
                    'lon' => -117.178,
                    'query' => '44.156.133.181',
                    'region' => 'CA',
                    'regionName' => 'California',
                    'status' => 'success',
                    'timezone' => 'America/Los_Angeles',
                    'zip' => '92111',
                ),
                78 => array('query' => '231.182.79.72', 'status' => 'fail',),
                79 => array(
                    'city' => 'Chiyoda',
                    'country' => 'Japan',
                    'countryCode' => 'JP',
                    'currency' => 'JPY',
                    'lat' => 35.694,
                    'lon' => 139.754,
                    'query' => '221.107.128.75',
                    'region' => '13',
                    'regionName' => 'Tokyo',
                    'status' => 'success',
                    'timezone' => 'Asia/Tokyo',
                    'zip' => '100-0001',
                ),
                80 => array('query' => '232.136.82.223', 'status' => 'fail',),
                81 => array(
                    'city' => 'Buffalo',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 42.9685,
                    'lon' => -78.7492,
                    'query' => '68.133.79.32',
                    'region' => 'NY',
                    'regionName' => 'New York',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '14221',
                ),
                82 => array(
                    'city' => 'Houston',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 29.7805,
                    'lon' => -95.5129,
                    'query' => '73.232.115.218',
                    'region' => 'TX',
                    'regionName' => 'Texas',
                    'status' => 'success',
                    'timezone' => 'America/Chicago',
                    'zip' => '77024',
                ),
                83 => array(
                    'city' => 'Columbus',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 39.9829,
                    'lon' => -82.9105,
                    'query' => '11.245.118.113',
                    'region' => 'OH',
                    'regionName' => 'Ohio',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '43218',
                ),
                84 => array('query' => '243.99.14.239', 'status' => 'fail',),
                85 => array(
                    'city' => 'Boston',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 42.3427,
                    'lon' => -71.0922,
                    'query' => '155.33.44.46',
                    'region' => 'MA',
                    'regionName' => 'Massachusetts',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '02115',
                ),
                86 => array(
                    'city' => 'Palo Alto',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 37.4146,
                    'lon' => -122.146,
                    'query' => '15.59.81.225',
                    'region' => 'CA',
                    'regionName' => 'California',
                    'status' => 'success',
                    'timezone' => 'America/Los_Angeles',
                    'zip' => '94304',
                ),
                87 => array(
                    'city' => 'Platte',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 43.4251,
                    'lon' => -98.9479,
                    'query' => '208.53.193.173',
                    'region' => 'SD',
                    'regionName' => 'South Dakota',
                    'status' => 'success',
                    'timezone' => 'America/Chicago',
                    'zip' => '57369',
                ),
                88 => array(
                    'city' => 'Palo Alto',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 37.4146,
                    'lon' => -122.146,
                    'query' => '15.87.28.33',
                    'region' => 'CA',
                    'regionName' => 'California',
                    'status' => 'success',
                    'timezone' => 'America/Los_Angeles',
                    'zip' => '94304',
                ),
                89 => array(
                    'city' => 'Rahway',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 40.6123,
                    'lon' => -74.267,
                    'query' => '54.128.36.11',
                    'region' => 'NJ',
                    'regionName' => 'New Jersey',
                    'status' => 'success',
                    'timezone' => 'America/New_York',
                    'zip' => '07065',
                ),
                90 => array('query' => '230.140.63.88', 'status' => 'fail',),
                91 => array(
                    'city' => 'Hermosillo',
                    'country' => 'Mexico',
                    'countryCode' => 'MX',
                    'currency' => 'MXN',
                    'lat' => 29.0982,
                    'lon' => -110.9747,
                    'query' => '189.173.147.116',
                    'region' => 'SON',
                    'regionName' => 'Sonora',
                    'status' => 'success',
                    'timezone' => 'America/Hermosillo',
                    'zip' => '83334',
                ),
                92 => array(
                    'city' => 'Chiyoda',
                    'country' => 'Japan',
                    'countryCode' => 'JP',
                    'currency' => 'JPY',
                    'lat' => 35.694,
                    'lon' => 139.754,
                    'query' => '219.195.73.213',
                    'region' => '13',
                    'regionName' => 'Tokyo',
                    'status' => 'success',
                    'timezone' => 'Asia/Tokyo',
                    'zip' => '100-0001',
                ),
                93 => array(
                    'city' => 'Beijing',
                    'country' => 'China',
                    'countryCode' => 'CN',
                    'currency' => 'CNY',
                    'lat' => 39.9042,
                    'lon' => 116.407,
                    'query' => '121.39.149.24',
                    'region' => 'BJ',
                    'regionName' => 'Beijing',
                    'status' => 'success',
                    'timezone' => 'Asia/Shanghai',
                    'zip' => '',
                ),
                94 => array(
                    'city' => 'Jinan',
                    'country' => 'China',
                    'countryCode' => 'CN',
                    'currency' => 'CNY',
                    'lat' => 36.6685,
                    'lon' => 117.02,
                    'query' => '182.44.32.220',
                    'region' => 'SD',
                    'regionName' => 'Shandong',
                    'status' => 'success',
                    'timezone' => 'Asia/Shanghai',
                    'zip' => '',
                ),
                95 => array(
                    'city' => 'Washington',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 38.6536,
                    'lon' => -87.1707,
                    'query' => '216.252.36.175',
                    'region' => 'IN',
                    'regionName' => 'Indiana',
                    'status' => 'success',
                    'timezone' => 'America/Indiana/Vincennes',
                    'zip' => '47501',
                ),
                96 => array(
                    'city' => 'Macquarie Park',
                    'country' => 'Australia',
                    'countryCode' => 'AU',
                    'currency' => 'AUD',
                    'lat' => -33.7842,
                    'lon' => 151.121,
                    'query' => '110.33.40.98',
                    'region' => 'NSW',
                    'regionName' => 'New South Wales',
                    'status' => 'success',
                    'timezone' => 'Australia/Sydney',
                    'zip' => '2113',
                ),
                97 => array(
                    'city' => 'Frankfurt am Main',
                    'country' => 'Germany',
                    'countryCode' => 'DE',
                    'currency' => 'EUR',
                    'lat' => 50.1109,
                    'lon' => 8.68213,
                    'query' => '217.49.230.132',
                    'region' => 'HE',
                    'regionName' => 'Hesse',
                    'status' => 'success',
                    'timezone' => 'Europe/Berlin',
                    'zip' => '60313',
                ),
                98 => array(
                    'city' => 'Roselle',
                    'country' => 'United States',
                    'countryCode' => 'US',
                    'currency' => 'USD',
                    'lat' => 41.9755,
                    'lon' => -88.0878,
                    'query' => '50.240.170.161',
                    'region' => 'IL',
                    'regionName' => 'Illinois',
                    'status' => 'success',
                    'timezone' => 'America/Chicago',
                    'zip' => '60172',
                ),
                99 => array(
                    'city' => 'Utrecht',
                    'country' => 'Netherlands',
                    'countryCode' => 'NL',
                    'currency' => 'EUR',
                    'lat' => 52.0927,
                    'lon' => 5.14937,
                    'query' => '145.166.46.140',
                    'region' => 'UT',
                    'regionName' => 'Utrecht',
                    'status' => 'success',
                    'timezone' => 'Europe/Amsterdam',
                    'zip' => '3583',
                ),
            ),
        ];
    }

    public static function expectedInDatabase()
    {
        $expectedInDatabase = [];

        foreach(self::data()['output'] as $request){
            if($request['status'] !== 'success') continue;

            $requestForExpectedInDatabase = [];

            foreach($request as $key => $value){

                $continue = false;

                switch($key){
                    case 'country';
                        $requestForExpectedInDatabase['country_name'] = $value;
                        $continue = true;
                        break;
                    case 'countryCode';
                        $requestForExpectedInDatabase['country_code'] = $value;
                        $continue = true;
                        break;
                    case 'zip';
                        $requestForExpectedInDatabase['postal_code'] = $value;
                        $continue = true;
                        break;
                    case 'lat';
                        $requestForExpectedInDatabase['latitude'] = $value;
                        $continue = true;
                        break;
                    case 'lon';
                        $requestForExpectedInDatabase['longitude'] = $value;
                        $continue = true;
                        break;
                    case 'query';
                        $requestForExpectedInDatabase['ip_address'] = $value;
                        $continue = true;
                        break;
                }

                if($continue){
                    continue;
                }

                $requestForExpectedInDatabase[$key] = $value;
            }

            $expectedInDatabase[] = $requestForExpectedInDatabase;
        }

        return $expectedInDatabase;
    }
}
